"""Creative reasoning layer."""

from .documentary_viability import (
    DocumentaryViabilityConfig,
    DocumentaryViabilityDecision,
    DocumentaryViabilityEngine,
    DocumentaryViabilityReport,
    ViabilityCategoryScore,
)
from .content_scheduler import (
    AutonomousContentScheduler,
    ContentHistoryRecord,
    ContentHistoryStore,
    ContentSchedulerConfig,
    ScheduledCandidate,
    SchedulerResult,
    SchedulingDecision,
    TopicIdentity,
    topic_identity,
)
from .topic_metadata import (
    TopicCategory,
    TopicClassification,
    TopicMetadata,
    build_topic_metadata,
    classify_topic,
)
from .topic_sources import (
    JsonTopicSource,
    TextTopicSource,
    TopicCardSource,
    TopicCandidate,
    TopicSource,
    load_topic_sources,
    topic_source_for_path,
)
from .topic_cards import (
    DEFAULT_TOPIC_CARD_PATH,
    DEFAULT_TOPIC_CARD_SOURCE,
    PILLAR_ALLOCATION,
    TopicCard,
    TopicCardCatalog,
    load_topic_card_catalog,
    load_topic_cards,
)
from .topic_bank import (
    TopicBankRecord,
    TopicBankStateStore,
    TopicBankStatus,
)
from .source_coverage import (
    SceneCoverage,
    SourceCoverageConfig,
    SourceCoverageDecision,
    SourceCoverageEvaluator,
    SourceCoverageReport,
    sample_scene_indexes,
    verified_critical_scene_coverage,
)
from .exact_subject_gate import (
    ExactSubjectAvailabilityGate,
    ExactSubjectGateConfig,
    ExactSubjectGateDecision,
    ExactSubjectGateReport,
    SubjectDefinition,
    subject_definition_from_pipeline,
)

__all__ = [
    "DocumentaryViabilityConfig",
    "DocumentaryViabilityDecision",
    "DocumentaryViabilityEngine",
    "DocumentaryViabilityReport",
    "AutonomousContentScheduler",
    "ContentHistoryRecord",
    "ContentHistoryStore",
    "ContentSchedulerConfig",
    "JsonTopicSource",
    "ScheduledCandidate",
    "SchedulerResult",
    "SchedulingDecision",
    "TextTopicSource",
    "TopicCard",
    "TopicCardCatalog",
    "TopicCardSource",
    "TopicCandidate",
    "TopicIdentity",
    "TopicSource",
    "TopicBankRecord",
    "TopicBankStateStore",
    "TopicBankStatus",
    "TopicCategory",
    "TopicClassification",
    "TopicMetadata",
    "ViabilityCategoryScore",
    "build_topic_metadata",
    "classify_topic",
    "load_topic_sources",
    "load_topic_card_catalog",
    "load_topic_cards",
    "topic_identity",
    "topic_source_for_path",
    "SceneCoverage",
    "SourceCoverageConfig",
    "SourceCoverageDecision",
    "SourceCoverageEvaluator",
    "SourceCoverageReport",
    "sample_scene_indexes",
    "verified_critical_scene_coverage",
    "ExactSubjectAvailabilityGate",
    "ExactSubjectGateConfig",
    "ExactSubjectGateDecision",
    "ExactSubjectGateReport",
    "SubjectDefinition",
    "subject_definition_from_pipeline",
    "DEFAULT_TOPIC_CARD_PATH",
    "DEFAULT_TOPIC_CARD_SOURCE",
    "PILLAR_ALLOCATION",
]
