"""Media selection and processing helpers."""

from .planning import (
    CapabilityRequirement,
    ProviderCapability,
    ProviderCapabilityRegistry,
    ProviderSearchPlan,
    QueryPlan,
    QueryPlanner,
    SearchStrategy,
    SceneType,
    SourcePlanner,
    classify_scene_type,
    default_provider_capability_registry,
)
from .selection import (
    CandidateScore,
    MediaSelectionResult,
    SceneImportance,
    StockCandidate,
    VisualIntent,
    build_visual_intent,
    candidate_from_local_path,
    candidate_from_nasa_item,
    candidate_from_pexels_video,
    candidate_from_pixabay_hit,
    candidate_from_remote_item,
    score_candidate,
    select_best_candidate,
    select_first_available_provider,
)

__all__ = [
    "CapabilityRequirement",
    "CandidateScore",
    "MediaSelectionResult",
    "ProviderCapability",
    "ProviderCapabilityRegistry",
    "ProviderSearchPlan",
    "QueryPlan",
    "QueryPlanner",
    "SearchStrategy",
    "SceneImportance",
    "SceneType",
    "SourcePlanner",
    "StockCandidate",
    "VisualIntent",
    "build_visual_intent",
    "classify_scene_type",
    "candidate_from_local_path",
    "candidate_from_nasa_item",
    "candidate_from_pexels_video",
    "candidate_from_pixabay_hit",
    "candidate_from_remote_item",
    "score_candidate",
    "select_best_candidate",
    "select_first_available_provider",
    "default_provider_capability_registry",
]
