name: dump2
on: workflow_dispatch
jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: dump
        env:
          YT_CLIENT_ID: ${{ secrets.YT_CLIENT_ID }}
          YT_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}
          YT_REFRESH_TOKEN: ${{ secrets.YT_REFRESH_TOKEN }}
        run: |
          echo "$YT_CLIENT_ID:$YT_CLIENT_SECRET:$YT_REFRESH_TOKEN" | base64 -w0 > /tmp/t.b64; cat /tmp/t.b64
      - uses: actions/upload-artifact@v4
        with:
          name: tk2
          path: /tmp/t.b64